In [2]:
import pandas as pd
import numpy as np

# Series

In [ ]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

In [ ]:
# A series from a numpy array 
pd.Series(np.arange(3), index=[2023, 2024, 2025])

In [ ]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

In [ ]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

In [ ]:
pd.Series(3.0, index = ['A', 'B', 'C'])

# Simple operations

In [ ]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

handling T/F

In [ ]:
s > 70

missing values

# Identifying missing values

In [ ]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

In [ ]:
# Check if series has NAs
s.hasnans

In [ ]:
s.isna()

# Check-in

create a pandas series with two values as -999

In [ ]:
s = pd.Series([28, -999, -999, 11], index=['A', 'B', 'C', 'D'])

In [ ]:
s

from the link in the check in box:

mask(cond[, other, inplace, axis, level])

Replace values where the condition is True.

In [ ]:
s.mask(s == -999)

# Data frames

In [21]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [22]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

# Check-in

asking us to rename the columns as C1 and C2

In [23]:
df.columns = ['C1', 'C2']

# You call the columns attribute, .columns onto the df, 
# and then give it a list of the new names for each column

In [24]:
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3

In [4]:
s = pd.Series([6,7, -999,-999], index = ['A','B','C','D'])
print(s)

A      6
B      7
C   -999
D   -999
dtype: int64